version: '3.8'

services:
  backend:
    build:
      context: ./demo
      dockerfile: Dockerfile
    container_name: backend_container
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_container:3306/demo-db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=demo-user
      - SPRING_DATASOURCE_PASSWORD=demo-password
    ports:
      - "8081:8081"
    networks:
      - app-network

  frontend:
    build:
      context: ./demo-front
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://backend_container:8081
    container_name: frontend_container
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: demo-password
      MYSQL_DATABASE: demo-db
      MYSQL_USER: demo-user
      MYSQL_PASSWORD: demo-password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
