spring.application.name=demo
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/demo-db}
spring.datasource.username=${DATABASE_USER:demo-user}
spring.datasource.password=${DATABASE_PASSWORD:demo-password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
